Notifications List component
near/near-discovery-components pull request #176
Opened 2023-08-11 19:43 UTC by marcinbodnar

It's not the final version of the component, but it's the proper layout for further work.

2023-08-14 11:27 UTC, shelegdmitriy requested changes

2023-08-14 11:27 UTC, shelegdmitriy commented on src/NearOrg/Notifications/NotificationsBanner.jsx
> +const bellIcon = (
Let's remove this icon from here and this use https://phosphoricons.com instead

2023-08-14 11:27 UTC, shelegdmitriy commented on src/NearOrg/Notifications/NotificationsBanner.jsx
> +      <Icon>{bellIcon}</Icon>
```suggestion
      <Icon>
        <i class="ph ph-bell-ringing" />
      </Icon>
```

2023-08-14 11:27 UTC, shelegdmitriy commented on src/NearOrg/Notifications/NotificationsBanner.jsx
> +    <Close>{closeIcon}</Close>
```suggestion
    <Close>
      <i class="ph ph-x" />
    </Close>
```

2023-09-17 13:36 UTC, charleslavon commented
@marcinbodnar should this PR be closed in favor of #330?

2023-09-18 15:22 UTC, closed without merging