added ndc nomination to featured components
near/near-discovery-components pull request #178
Opened 2023-08-12 13:56 UTC by codingshot

added ndc nomination under featured components under devhub

2023-08-14 12:06 UTC, shelegdmitriy requested changes

2023-08-14 12:06 UTC, shelegdmitriy commented on src/FeaturedComponents.jsx
> +        />
```suggestion
      </Item>
      <Item>
        <Widget
          src="${REPL_ACCOUNT}/widget/ComponentCard"
          props={{ src: "nomination.ndctools.near/widget/NDC.Nomination.Page" }}
        />
```

2023-08-14 20:12 UTC, charleslavon commented on src/FeaturedComponents.jsx
> +          props={{ src: "nomination.ndctools.near/widget/NDC.Nomination.Page" }}
@codingshot do you have a testnet version of this component? If so, please commit an update to the replacements.*.json files as mentioned in [this PR](https://github.com/near/near-discovery-components/pull/167#discussion_r1293855988) which you can use as a reference.

2023-08-16 18:53 UTC, mpeterdev commented
closing since a simpler process for adding featured components will be landing soon with #183

2023-08-16 19:01 UTC, TiffanyGYJ commented
@mpeterdev NDC widget adding is time sensitive as the nomination and voting will be within this month, if this update for pull request by code/shot suffice our need, can we merge this for now?

2023-08-16 19:12 UTC, mpeterdev commented
> @mpeterdev NDC widget adding is time sensitive as the nomination and voting will be within this month, if this update for pull request by code/shot suffice our need, can we merge this for now?

This PR could be merged, but it conflicts with the changes made in #183 so it would be ideal not to merge it. The only thing we are waiting on to roll #183 to prod is for our management account for be funded by Pagoda bizops so we can ping them to move it along

2023-08-16 19:15 UTC, closed without merging