encourage the creation of custom profile components
near/near-discovery-components pull request #331
Opened 2023-09-17 14:08 UTC by charleslavon

This PR updates ProfilePage to redirect to an accountId's custom profile page if it exists.

2023-09-18 10:04 UTC, shelegdmitriy requested changes

2023-09-18 10:04 UTC, shelegdmitriy commented on src/ProfilePage.jsx
> +}
@charleslavon could you please apply formatting here?

2023-09-18 23:34 UTC, gabehamilton approved these changes

2023-09-19 00:49 UTC, gabehamilton commented
Was thinking about this more. Maybe this could use a wrapper (tabs?) such that the viewing user can switch between the custom profile component and the standard one? The standard one may serve as a source of truth about users.

2023-09-19 12:52 UTC, shelegdmitriy approved these changes

2023-09-19 12:55 UTC, shelegdmitriy commented
@gabehamilton sounds interesting. But let's move this to the discussions, @charleslavon WDYT?

2023-09-19 20:06 UTC, thisisjoshford commented
uh-mazing @charleslavon ! 💪 Thank you so much for putting some time in on your weekend off to hack on this! 🙏

@gabehamilton I like your idea for adding more options here (re: tabs/toggle) and also have some ideas as far as wanting to standardize _some_ things on the profile page such as contact info, contribution graph, profile image, sponsor/tip button etc. This way the most common things people want to find are highly discoverable and people don't have to play "Where's Waldo" if they wanna reach out to a dev or tip them.

I'm a big fan of being Aglie and shipping small incremental improvements rather than blocking progress here. IMO we should ship this as is (or make a minor tweak if needed) and then think more deeply about this with the design team (@heycorwin @sarahmills) 

cc @ravigautham

2023-09-19 20:06 UTC, thisisjoshford approved these changes
uh-mazing @charleslavon ! 💪 Thank you so much for putting some time in on your weekend off to hack on this! 🙏

@gabehamilton I like your idea for adding more options here (re: tabs/toggle) and also have some ideas as far as wanting to standardize _some_ things on the profile page such as contact info, contribution graph, profile image, sponsor/tip button etc. This way the most common things people want to find are highly discoverable and people don't have to play "Where's Waldo" if they wanna reach out to a dev or tip them.

I'm a big fan of being Aglie and shipping small incremental improvements rather than blocking progress here. IMO we should ship this as is (or make a minor tweak if needed) and then think more deeply about this with the design team (@heycorwin @sarahmills) 

cc @ravigautham

2023-09-20 13:18 UTC, merged