#517 Moderate a post and first pass of new moderation page.
near/near-discovery-components pull request #372
Opened 2023-09-29 22:55 UTC by gabehamilton

* Tabbed moderation page
 * Moderate a post feature
 * Moderation actions are written in SocialDB index format
 * Un-moderate actions write a delete operation to the index. This is applied in the UI.

2023-10-04 19:41 UTC, calebjacob commented
Hey @gabehamilton, just for future reference, take a look at our DIG component library: https://near.org/near/widget/DIG.OverviewPage

In general, let's try and use these UI components going forward to help achieve a more consistent look and feel throughout the app. If you don't have the time right now, feel free to merge this PR and refactor to using the DIG components at a later time. :) If you have any questions or run into issues with a DIG component, let me know.

2023-10-04 21:05 UTC, gabehamilton commented
> Hey @gabehamilton, just for future reference, take a look at our DIG component library: https://near.org/near/widget/DIG.OverviewPage
> 
> In general, let's try and use these UI components going forward to help achieve a more consistent look and feel throughout the app. If you don't have the time right now, feel free to merge this PR and refactor to using the DIG components at a later time. :) If you have any questions or run into issues with a DIG component, let me know.

Great, thank you. There's a story coming up to put all this into a more useable form so Moderators can do their work off of the FlaggedFeed. I'll do that switch to the DIG components then.

2023-10-04 21:17 UTC, shelegdmitriy requested changes
Overall looks good! I left a couple of comments and could you please apply formatting?

And +1 to Caleb's comment. No need to refactor all the things right now but it's worth creating a task for that 🙂

2023-10-04 21:17 UTC, shelegdmitriy commented on src/Moderation/Moderator.jsx
> +const moderatorAccount = 'buildnear.testnet'; // testing // props?.moderatorAccount || "${REPL_MODERATOR}";
I think this should look like this:
```suggestion
const moderatorAccount = props?.moderatorAccount || "${REPL_MODERATOR}";
```

2023-10-04 21:17 UTC, shelegdmitriy commented on src/Moderation/Moderator.jsx
> +const baseUrl = `#/${REPL_ACCOUNT}/widget/Moderation.Moderator?`;
Let's move this `?` at the end of the string and add to the lines you're using `baseUrl`

```suggestion
const baseUrl = `#/${REPL_ACCOUNT}/widget/Moderation.Moderator`;
```

2023-10-04 21:17 UTC, shelegdmitriy commented on src/Moderation/Moderator.jsx
> +                    href={`${baseUrl}&tab=reported`}
Using change on line **69** change it in this way:

```suggestion
                    href={`${baseUrl}?&tab=reported`}
```

Please do the same for the lines bellow

2023-10-04 21:17 UTC, shelegdmitriy commented on src/Moderation/Moderator.jsx
> +                    src={`${REPL_ACCOUNT}/widget/Moderation.ModerateAccounts`}
No need to wrap ${REPL_ACCOUNT} with curly braces you did the right thing on line **109** 🙂

```suggestion
                    src="${REPL_ACCOUNT}/widget/Moderation.ModerateAccounts"
```

2023-10-05 20:05 UTC, shelegdmitriy commented on src/Moderation/ModeratePosts.jsx
> +  : // .filter((f) => f.accountId === moderatorAccount)
This line is commented in all three files, maybe let's clean this up then?

2023-10-05 20:06 UTC, shelegdmitriy approved these changes
LGTM!

2023-10-05 20:18 UTC, merged